---
title: "Lab 0 - Hello R!"
author: "Cooper Likosar"
date: "01/17/2023"
format: pdf
editor: visual
---

## Load Packages

```{r}
#| label: load-packages
#| message: false
library(tidyverse)
library(datasauRus)
```

## Exercise 1

There are 1846 rows. There are 3 variables which are the dataset, x-values, and y-values.

## Exercise 2

```{r}
#| label: plot-dino
#| fig-height: 5
#| fig-width: 5
dino_data <- datasaurus_dozen %>%
  filter(dataset == "dino")
ggplot(data = dino_data, mapping = aes(x = x, y = y)) + 
  geom_point()
```

```{r}
#| label: cor-dino
dino_data %>%
  summarize(r = cor(x, y))
```

## Exercise 3

```{r}
#| label: plot-circle
#| fig-height: 5
#| fig-width: 5
circle_data <- datasaurus_dozen %>%
  filter(dataset == "circle")
ggplot(data = circle_data, mapping = aes(x = x, y = y)) + 
  geom_point()
```

Very different plot than dino.

```{r}
#| label: cor-circle
circle_data %>%
  summarize(r = cor(x, y))
```

Very similar r value as dino (\~-0.06).

## Exercise 4

```{r}
#| label: plot-star
#| fig-height: 5
#| fig-width: 5
star_data <- datasaurus_dozen %>%
  filter(dataset == "star")
ggplot(data = star_data, mapping = aes(x = x, y = y)) + 
  geom_point()
```

Very different plot than dino.

```{r}
#| label: cor-star
star_data %>%
  summarize(r = cor(x, y))
```

Very similar r value as dino (\~-0.06).

## Exercise 5

```{r}
#| label: plot-dataset
#| fig-height: 10
#| fig-width: 6
ggplot(datasaurus_dozen, aes(x = x, y = y, color = dataset))+
  geom_point()+
  facet_wrap(~ dataset, ncol = 3) +
  theme(legend.position = "none")
```

All have very different plots/shapes.

```{r}
#| label: cor-dataset
datasaurus_dozen |>
  group_by(dataset) |>
  summarize(r = cor(x, y))
```

All have very similar/close r values (\~-0.06).
